---
name: "Claude Terminal"
description: "Terminal interface for Claude Code CLI with mobile support and Home Assistant MCP integration"
version: "1.5.3"
slug: "claude_terminal"
init: false

# Supported architectures
arch:
  - aarch64
  - amd64
  - armv7

# External resources
url: "https://github.com/anthropics/claude-code"

# Web interface configuration
ingress: true
ingress_port: 7681
panel_icon: mdi:code-braces
panel_title: "Claude Terminal"
panel_admin: true

# Port configuration
ports:
  7681/tcp: 7681
ports_description:
  7681/tcp: "Web terminal (not required for ingress)"

# Add-on configuration options
options:
  auto_launch_claude:
    name: "Auto-launch Claude"
    description: "Auto-start Claude on terminal open (disable for session picker)"
  auto_start_happy_daemon:
    name: "Auto-start Happy Daemon"
    description: "Automatically start Happy daemon in background for mobile connections"
  enable_mcp_integration:
    name: "Enable MCP Integration"
    description: "Auto-configure connection to Home Assistant MCP Server"
  mcp_access_token:
    name: "MCP Access Token"
    description: "Long-lived access token from Home Assistant (Profile → Security → Create Token)"
  mcp_server_url:
    name: "MCP Server URL"
    description: "Override MCP server URL (default: auto-discover). Example: http://homeassistant.local:8123/mcp_server/sse"
schema:
  auto_launch_claude: bool?
  auto_start_happy_daemon: bool?
  enable_mcp_integration: bool?
  mcp_access_token: password?
  mcp_server_url: str?

# Volume mappings for file access
map:
  - config:rw    # Access to Home Assistant configuration files

# API access for Home Assistant integration
hassio_api: true
hassio_role: manager
homeassistant_api: true
auth_api: true

# Service startup configuration
startup: services

# Web UI access URL
webui: http://[HOST]:[PORT:7681]/
